service: aws-uchimi
useDotenv: true
provider:
  name: aws
  runtime: nodejs24.x
  region: ap-southeast-1 
  environment:
    TABLE_NAME: ${env:TABLE_NAME}
    USER_TABLE: ${env:USER_TABLE}
    STUDY_TABLE: ${env:STUDY_TABLE}
    SOCIAL_TABLE: ${env:SOCIAL_TABLE}
    QUEST_TABLE: ${env:QUEST_TABLE}
    MINIGAME_TABLE: ${env:MINIGAME_TABLE}
    ITEMDATA_TABLE: ${env:ITEMDATA_TABLE}
    INVENTORY_TABLE: ${env:INVENTORY_TABLE}
    GACHAHISTORY_TABLE: ${env:GACHAHISTORY_TABLE}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:BatchWriteItem
          Resource: 
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:TABLE_NAME}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:USER_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:STUDY_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:SOCIAL_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:QUEST_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:MINIGAME_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:ITEMDATA_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:INVENTORY_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${env:GACHAHISTORY_TABLE}"
  httpApi:
    cors: true
    authorizers:
      myCognitoAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID}

functions:
  - ${file(./src/userFunction/function.yml)}
  - ${file(./src/sessionFunction/function.yml)}
  - ${file(./src/inventoryFunction/function.yml)}
  - ${file(./src/questFunction/function.yml)}